name: x402-settlements
description: Index all x402 payment settlements across Base and Solana
apiVersion: 3

sources:
  # ── Base: transactions TO x402 proxy contracts ──────────────────
  base_proxy_txs:
    type: dataset
    dataset_name: base.transactions
    version: 1.0.0
    start_at: earliest
    filter: >
      to_address IN (
        '0x4020615294c913f045dc10f0a5cdebd86c280001',
        '0x4020633461b2895a48930ff97ee8fcde8e520002'
      )

  # ── Base: ERC-20 Transfer logs (to extract payer/payee/amount) ──
  base_transfer_logs:
    type: dataset
    dataset_name: base.decoded_logs
    version: 1.0.0
    start_at: earliest
    filter: >
      event_signature = 'Transfer(address,address,uint256)'

transforms:
  # Join facilitator txs with transfer logs to get settlement details
  x402_settlements:
    sql: >
      SELECT
        t.hash as tx_hash,
        t.block_number,
        t.block_timestamp,
        'base' as network,
        CASE
          WHEN t.to_address = '0x4020615294c913f045dc10f0a5cdebd86c280001' THEN 'exact'
          WHEN t.to_address = '0x4020633461b2895a48930ff97ee8fcde8e520002' THEN 'upto'
          ELSE 'exact'
        END as scheme,
        t.from_address as facilitator,
        l.event_params_from as payer,
        l.event_params_to as payee,
        l.event_params_value as amount,
        l.address as token
      FROM base_proxy_txs t
      INNER JOIN base_transfer_logs l
        ON t.hash = l.transaction_hash
    primary_key: tx_hash

sinks:
  # Write to R2-compatible S3
  r2_settlements:
    type: file
    from: x402_settlements
    path: s3://x402-analytics/goldsky/
    format: json
    secret_name: R2_CREDENTIALS

resource_size: s
